name: detector-train-export

on:
  push:
    paths:
      - 'assets/**'
      - 'ml_pipeline/**'
      - '.github/workflows/detector-train-export.yml'
      - 'requirements.txt'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Python deps (CPU wheels)
        run: |
          python -m pip install --upgrade pip
          # Install PyTorch CPU version
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          # Install requirements
          pip install -r requirements.txt
          # Try to install TFJS deps, but don't fail if they're not available
          pip install onnx-tf tensorflow tensorflowjs || echo "TFJS dependencies not available, will use ONNX fallback"

      - name: Build dataset
        run: |
          python ml_pipeline/make_dataset.py \
            --assets-dir assets \
            --out out_dataset \
            --img-size 640 \
            --samples-per-piece 160

      - name: Train detector
        run: |
          python ml_pipeline/train.py \
            --data out_dataset \
            --out out_models/ssdlite320 \
            --epochs 12 \
            --batch-size 16 \
            --img-size 320

      - name: Export for web (prefer TFJS, fallback ONNX)
        run: |
          python ml_pipeline/export_tfjs.py \
            --onnx out_models/ssdlite320/best.onnx \
            --labels out_models/ssdlite320/labels.json \
            --out models \
            --public public \
            --prefer tfjs

      - name: Copy model files to public directory
        run: |
          # Ensure the models are in public/ so Vite will include them in dist/
          mkdir -p public/models
          if [ -d "models/detector" ]; then
            cp -r models/detector public/models/
            echo "Copied models/detector to public/models/"
          fi
          
          # Debug: Check what files we have
          echo "=== Checking generated files ==="
          echo "Root directory files:"
          ls -la model-manifest.json 2>/dev/null || echo "No model-manifest.json in root"
          echo ""
          echo "Public directory files:"
          ls -la public/model-manifest.json 2>/dev/null || echo "No model-manifest.json in public/"
          ls -la public/models/
          echo ""
          echo "Models directory:"
          ls -la models/ 2>/dev/null || echo "No models/ directory"

      - name: Verify model files before build
        run: |
          echo "=== Verifying files before build ==="
          if [ ! -f "public/model-manifest.json" ]; then
            echo "ERROR: public/model-manifest.json not found!"
            exit 1
          fi
          if [ ! -d "public/models/detector" ]; then
            echo "ERROR: public/models/detector/ not found!"
            exit 1
          fi
          echo "✅ All required files present"
          echo "Contents of public/:"
          ls -la public/
          echo "Contents of public/models/:"
          ls -la public/models/

      - name: Install Node dependencies
        run: npm ci

      - name: Build site with model
        run: npm run build

      - name: Verify build output
        run: |
          echo "=== Checking dist/ contents ==="
          echo "Root of dist/:"
          ls -la dist/
          echo ""
          echo "Looking for model files in dist/:"
          ls -la dist/model-manifest.json 2>/dev/null || echo "No model-manifest.json in dist/"
          ls -la dist/models/ 2>/dev/null || echo "No models/ in dist/"
          if [ -d "dist/models/detector" ]; then
            echo "Contents of dist/models/detector/:"
            ls -la dist/models/detector/
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-with-model
          path: dist/
          retention-days: 30

      # Deploy to GitHub Pages if on main branch
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4