name: detector-train-export

on:
  push:
    paths:
      - 'data/raw/**'
      - 'apps/web/public/data/art-content.*.json'
      - 'ml/**'
      - '.github/workflows/detector-train-export.yml'
      - 'ml/requirements.txt'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install Python deps (CPU wheels)
        run: |
          python -m pip install --upgrade pip
          # Install PyTorch CPU version
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          # Install requirements
          pip install -r ml/requirements.txt
          # Try to install TFJS deps, but don't fail if they're not available
          pip install onnx-tf tensorflow tensorflowjs || echo "TFJS dependencies not available, will use ONNX fallback"

      - name: Build dataset
        run: |
          python ml/make_dataset.py \
            --assets-dir data/raw/assets \
            --backgrounds-dir data/raw/backgrounds \
            --out artifacts/datasets \
            --img-size 640 \
            --samples-per-piece 160

      - name: Train detector
        run: |
          python ml/train.py \
            --data artifacts/datasets \
            --out artifacts/models/ssdlite320 \
            --epochs 12 \
            --batch-size 16 \
            --img-size 320

      - name: Export for web (prefer TFJS, fallback ONNX)
        run: |
          python ml/export_tfjs.py \
            --onnx artifacts/models/ssdlite320/best.onnx \
            --labels artifacts/models/ssdlite320/labels.json \
            --out apps/web/public/models \
            --public apps/web/public \
            --prefer tfjs

      - name: Copy model files to public directory
        run: |
          # Ensure the models are in apps/web/public/ so Vite will include them in dist/
          mkdir -p apps/web/public/models
          if [ -d "apps/web/public/models/detector" ]; then
            echo "Models already exported to apps/web/public/models/detector/"
          fi
          
          # Debug: Check what files we have
          echo "=== Checking generated files ==="
          echo "Contents of apps/web/public/:"
          ls -la apps/web/public/
          echo ""
          echo "Contents of apps/web/public/models/:"
          ls -la apps/web/public/models/ 2>/dev/null || echo "No exported models"

      - name: Verify model files before build
        run: |
          echo "=== Verifying files before build ==="
          if [ ! -f "apps/web/public/model-manifest.json" ]; then
            echo "ERROR: apps/web/public/model-manifest.json not found!"
            exit 1
          fi
          if [ ! -d "apps/web/public/models/detector" ]; then
            echo "ERROR: apps/web/public/models/detector/ not found!"
            exit 1
          fi
          echo "✅ All required files present"
          echo "Contents of apps/web/public/:"
          ls -la apps/web/public/
          echo "Contents of apps/web/public/models/:"
          ls -la apps/web/public/models/

      - name: Install Node dependencies
        working-directory: apps/web
        run: npm ci

      - name: Build site with model
        working-directory: apps/web
        run: npm run build

      - name: Verify build output
        run: |
          echo "=== Checking dist/ contents ==="
          echo "Root of dist/:"
          ls -la apps/web/dist/
          echo ""
          echo "Looking for model files in dist/:"
          ls -la apps/web/dist/model-manifest.json 2>/dev/null || echo "No model-manifest.json in dist/"
          ls -la apps/web/dist/models/ 2>/dev/null || echo "No models/ in dist/"
          if [ -d "apps/web/dist/models/detector" ]; then
            echo "Contents of dist/models/detector/:"
            ls -la apps/web/dist/models/detector/
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-with-model
          path: apps/web/dist/
          retention-days: 30

      # Deploy to GitHub Pages if on main branch
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/dist/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
